### ISSUE TITLE
Replace current GeoJSON SVG map with one that does not contain political boundaries

### ISSUE THREAD

**Issue by emilyfuhrman** [emilyfuhrman/F2015020#6]

**Comment by JohannGillium** [comment]
Hi Emily,

I just added to the repository the file world.continents.geo.json in the data folder, file which seems perfect for our needs. Unfortunately, as this geo.json file's structure is very different from the former countries.json -though it is a geo.json -, we can not just replace one by the other, and have your d3 script working. So either I adapt world.continents.geo.json to make it with the same structure as countries.json, either you change a little your script, to make it handle that new map...

As you're far skilled than I am for this, I would prefer that you take first a look to this new geo.json file, because I figure that it would be easier for you to adapt you script to the new data than for me to adapt the whole structure of the map.

But first you can see what it looks like in SVG : http://code.highcharts.com/mapdata/1.0.0/custom/world-continents.svg. And see if you think that it will do the trick.

**Comment by emilyfuhrman** [comment]
This looks great, thank you! 

I will adapt this to the current code, but feel free to take a pass at it yourself (just work in a different branch) so you can become more familiar with it too.
